export const SAVE_STARTUP_PARAM = 'SAVE_STARTUP_PARAM';

export const SUCCESS_AUTH  = 'SUCCESS_ATUH';

export const ADD_TO_CART = 'ADD_TO_CART';

export const CLEAR_CART = 'CLEAR_CART';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const INCREASE_CART_ITEM_QTY = 'INCREASE_CART_ITEM_QTY';
export const DECREASE_CART_ITEM_QTY = 'DECREASE_CART_ITEM_QTY';
export const CHANGE_CART_ITEM_QTY = 'CHANGE_CART_ITEM_QTY';